import React from "react";
import Head from "next/head";
import Nav from "../Nav/Nav";
import { ThemeProvider, createTheme } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";

export default function Layout({ children }: any) {
    const darkTheme = createTheme({
        palette: {
            mode: "dark",
        },
    });
    return (
        <>
            <ThemeProvider theme={darkTheme}>
                <CssBaseline />

                <Head>
                    <title>TrandWatch</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Nav />
                <main>{children}</main>
            </ThemeProvider>
        </>
    );
}
