import { Items } from "../../types";
const items: Items = [
    {
        id: "1",
        brand: "Rolex",
        name: "Day Date",
        price: "45 000€",
        subname: "L'accomplissement d'un idéal",
        image: "/rolex/daydate.png",
        video: "/rolex/video/daydate.mp4",
        desc1: "Connue pour être « la montre des présidents » d’hier et des leaders de demain, la Day‑Date est au poignet d’hommes et de femmes d’exception qui dédient leur existence à l’accomplissement de leurs idéaux. Les époques se succèdent, mais elle est toujours à la place qui l’a vue naître, à la pointe de la modernité.",
        cname: "Jean Dupont",
        cphone: "06 67 34 50 90",
        cemail: "jean.dupont@gmail.com",
    },
    {
        id: "2",
        brand: "Rolex",
        name: "Oyster Perpetual",
        price: "55 000€",
        subname: "L'essence de l'Olyster",
        image: "/rolex/oysterperpetual.png",
        video: "/rolex/video/olyster.mp4",
        desc1: "Héritières directes de l’Oyster d’origine, la première montre-bracelet étanche au monde, sur laquelle Rolex a bâti sa réputation depuis 1926, les montres de la gamme Oyster Perpetual bénéficient des attributs fondamentaux de la collection Oyster Perpetual, à savoir une excellente précision chronométrique, l’étanchéité du boîtier Oyster et le remontage automatique du mouvement par rotor Perpetual. Affichant les heures, les minutes et les secondes, réalisées exclusivement en acier Oystersteel et présentant des finitions soignées, elles figurent la forme la plus épurée du chronomètre de poignet. Le traitement antireflet appliqué au dos de la glace saphir sur la nouvelle génération de l’Oyster Perpetual permet une lecture optimale du cadran.",
        cname: "Micheal Fox",
        cphone: "06 22 54 60 80",
        cemail: "micheal.fox@yahoo.com",
    },
    {
        id: "3",
        brand: "Rolex",
        name: "Submariner",
        price: "35 000€",
        subname: "L'exploratrice des profondeurs",
        image: "/rolex/submariner.png",
        video: "/rolex/video/submariner.mp4",
        desc1: "Lorsqu’elle est lancée en 1953, la Submariner est la première montre‑bracelet de plongée étanche à 100 mètres de profondeur. Elle symbolise une seconde révolution dans la maîtrise technique de l’étanchéité, après l’invention de l’Oyster en 1926 – la première montre‑bracelet étanche au monde. La Submariner marque un tournant historique dans le monde de l’horlogerie et s’impose rapidement parmi les montres de plongée. La Submariner est aujourd’hui étanche jusqu’à 300 mètres.",
        cname: "Montana Parks",
        cphone: "06 75 72 99 99",
        cemail: "quisque.porttitor@outlook.com",
    },
    {
        id: "4",
        brand: "Rolex",
        name: "GMT Master II",
        price: "35 000€",
        subname: "La montre cosmopolite",
        image: "/rolex/gmtmaster.jpg",
        video: "/rolex/video/gmt.mp4",
        desc1: "Conçue pour afficher simultanément l’heure de deux fuseaux horaires, la GMT‑Master, qui a vu le jour en 1955, a été développée comme un instrument d’aide à la navigation pour les professionnels appelés à sillonner le monde. Héritière du modèle original, la GMT‑Master II a été dévoilée en 1982, avec un nouveau mouvement garantissant une utilisation aisée. Sa fonctionnalité sans pareille, sa robustesse et son esthétique instantanément reconnaissable ont convaincu les globe-trotteurs du monde entier.",
        cname: "Jocelyn Swanson",
        cphone: "02 77 38 78 31",
        cemail: "sodales.at@google.com",
    },
    {
        id: "5",
        brand: "Rolex",
        name: "Explorer II",
        price: "35 000€",
        subname: "L'appel des sommets",
        image: "/rolex/explorer.jpg",
        video: "/rolex/video/explorer.mp4",
        desc1: "Des explorateurs, alpinistes et scientifiques parmi les plus intrépides ont éprouvé la fiabilité des montres Explorer et Explorer II dans des endroits aux conditions les plus extrêmes.",
        cname: "Cheryl Dorsey",
        cphone: "08 37 52 44 74",
        cemail: "lorem.luctus@aol.net",
    },
    {
        id: "7",
        brand: "Rolex",
        name: "Yacht-Master II",
        price: "35 000€",
        subname: "La montre du grand large",
        image: "/rolex/yachtmaster.jpg",
        video: "/rolex/video/yatch.mp4",
        desc1: "Les modèles Rolex Yacht‑Master et Yacht‑Master II incarnent l’esprit marin. Témoin des liens privilégiés qui unissent Rolex et le monde de la voile depuis les années 1950, la Yacht‑Master conjugue avec brio fonctionnalité et style nautique, tandis que la Yacht‑Master II propose un concentré de technologie Rolex à l’avant‑garde de l’art horloger dans un chronographe de régate conçu pour la voile de compétition.",
        cname: "Sade Sexton",
        cphone: "04 34 43 96 07",
        cemail: "cubilia.curae@icloud.com",
    },
    {
        id: "8",
        brand: "Rolex",
        name: "Datejust",
        price: "35 000€",
        subname: "La montre qui fait date",
        image: "/rolex/datejust.jpg",
        video: "/rolex/video/datejust.mp4",
        desc1: "Chaque jour peut durablement marquer le parcours d’une vie, ouvrir la voie à de nouvelles aspirations, changer le cours d’un destin ou de l’Histoire. Depuis sa création en 1945, l’Oyster Perpetual Datejust n’a cessé de se réinventer tout en symbolisant une certaine élégance classique. Jalon important de l’histoire horlogère, elle est la première montre‑bracelet chronomètre, automatique et étanche à afficher la date dans un guichet à 3 heures sur le cadran. Mis en valeur par la loupe Cyclope, ces chiffres nous rappellent que vingt‑quatre heures ne s’écoulent pas seulement pour former un jour, mais pour faire date.",
        cname: "Dorian Kinney",
        cphone: "04 72 08 11 78",
        cemail: "posuere.at@yahoo.com",
    },
    {
        id: "9",
        brand: "Rolex",
        name: "Milgauss",
        price: "35 000€",
        subname: "La science à l'honneur",
        image: "/rolex/milgauss.jpg",
        video: "/rolex/video/milgauss.mp4",
        desc1: "Conçue en 1956 pour répondre aux besoins des ingénieurs et des scientifiques, l’Oyster Perpetual Milgauss est une montre pionnière dans la résistance aux champs magnétiques, capable de supporter des interférences allant jusqu’à 1000 gauss, d’où son nom.",
        cname: "Macaulay Salas",
        cphone: "08 51 12 55 86",
        cemail: "commodo.hendrerit@protonmail.com",
    },
    {
        id: "10",
        brand: "Rolex",
        name: "Air-King",
        price: "35 000€",
        subname: "Un hommage à l'aviation",
        image: "/rolex/airking.jpg",
        video: "/rolex/video/airking.mp4",
        desc1: "L’Oyster Perpetual Air‑King est une montre de référence pour les pilotes, les navigateurs et les amateurs d’aviation. Elle a été conçue en 1957 pour répondre aux besoins des pilotes de ligne, qui recherchaient une montre de précision, facile à lire et étanche. Elle a été baptisée Air‑King en hommage à la compagnie aérienne Pan Am, qui a été la première à utiliser des Rolex Oyster Perpetual dans ses avions.",
        cname: "Charles Morris",
        cphone: "06 10 54 57 67",
        cemail: "sagittis.felis@outlook.com",
    },
    {
        id: "11",
        brand: "Tag Heuer",
        name: "Carrera",
        price: "4 000€",
        subname: "L'explorateur des profondeurs",
        image: "/tagheuer/carrera.png",
        cname: "Xander Barker",
        cphone: "05 84 02 65 55",
        cemail: "malesuada.malesuada@outlook.com",
    },
    {
        id: "12",
        brand: "Tag Heuer",
        name: "Monaco",
        price: "35 000€",
        subname: "L'explorateur des profondeurs",
        image: "/tagheuer/monaco.jpg",
        cname: "Tatiana Sandoval",
        cphone: "04 14 74 95 01",
        cemail: "vitae@icloud.edu",
    },
    {
        id: "13",
        brand: "Tag Heuer",
        name: "Grand Carrera",
        price: "35 000€",
        subname: "L'explorateur des profondeurs",
        image: "/tagheuer/grandcarrera.jpg",
        cname: "Kenyon Huff",
        cphone: "07 45 37 11 01",
        cemail: "ante@google.org",
    },
    {
        id: "14",
        brand: "Tag Heuer",
        name: "Formula 1",
        price: "35 000€",
        subname: "L'explorateur des profondeurs",
        image: "/tagheuer/formula1.jpg",
        cname: "Porter Flores",
        cphone: "03 46 76 16 67",
        cemail: "nisi@hotmail.couk",
    },
    {
        id: "15",
        brand: "Tag Heuer",
        name: "Link",
        price: "35 000€",
        subname: "L'explorateur des profondeurs",
        image: "/tagheuer/link.jpg",
        cname: "Regina Herring",
        cphone: "04 28 25 33 16",
        cemail: "consectetuer@hotmail.com",
    },
    {
        id: "16",
        brand: "Tag Heuer",
        name: "Aquaracer",
        price: "35 000€",
        subname: "L'explorateur des profondeurs",
        image: "/tagheuer/aquaracer.jpg",
        cname: "Marvin Waters",
        cphone: "05 25 33 53 33",
        cemail: "sagittis.placerat@outlook.couk",
    },
];

export default items;
