import { Items } from "../../types";
const items: Items = [
    {
        id: "1",
        brand: "Rolex",
        name: "Day Date",
        price: "45 000€",
        subname: "L'accomplissement d'un idéal",
        image: "/rolex/daydate.png",
        video: "/rolex/video/daydate.mp4",
        desc1: "",
        cname: "Jean",
        cphone: "06 00 00 00 00",
        cemail: "jean.gmail.com",
    },
    {
        id: "2",
        brand: "Rolex",
        name: "Oyster Perpetual",
        price: "55 000€",
        subname: "L'essence de l'Olyster",
        image: "/rolex/oysterperpetual.png",
    },
    {
        id: "3",
        brand: "Rolex",
        name: "Submariner",
        price: "35 000€",
        subname: "L'explorateur des profondeurs",
        image: "/rolex/submariner.png",
    },
    {
        id: "4",
        brand: "Rolex",
        name: "GMT Master II",
        price: "35 000€",
        subname: "L'explorateur des profondeurs",
        image: "/rolex/gmtmaster.jpg",
    },
    {
        id: "5",
        brand: "Rolex",
        name: "Explorer II",
        price: "35 000€",
        subname: "L'explorateur des profondeurs",
        image: "/rolex/explorer.jpg",
    },
    {
        id: "6",
        brand: "Rolex",
        name: "Sea Dweller",
        price: "35 000€",

        subname: "L'explorateur des profondeurs",
        image: "/rolex/seadweller.jpg",
    },
    {
        id: "7",
        brand: "Rolex",
        name: "Yacht-Master II",
        price: "35 000€",
        subname: "L'explorateur des profondeurs",
        image: "/rolex/yachtmaster.jpg",
    },
    {
        id: "8",
        brand: "Rolex",
        name: "Datejust",
        price: "35 000€",
        subname: "L'explorateur des profondeurs",
        image: "/rolex/datejust.jpg",
    },
    {
        id: "9",
        brand: "Rolex",
        name: "Milgauss",
        price: "35 000€",
        subname: "L'explorateur des profondeurs",
        image: "/rolex/milgauss.jpg",
    },
    {
        id: "10",
        brand: "Rolex",
        name: "Air-King",
        price: "35 000€",
        subname: "L'explorateur des profondeurs",
        image: "/rolex/airking.jpg",
    },
    {
        id: "11",
        brand: "Tag Heuer",
        name: "Carrera",
        price: "4 000€",
        subname: "L'explorateur des profondeurs",
        image: "/tagheuer/carrera.png",
    },
    {
        id: "12",
        brand: "Tag Heuer",
        name: "Monaco",
        price: "35 000€",
        subname: "L'explorateur des profondeurs",
        image: "/tagheuer/monaco.jpg",
    },
    {
        id: "13",
        brand: "Tag Heuer",
        name: "Grand Carrera",
        price: "35 000€",
        subname: "L'explorateur des profondeurs",
        image: "/tagheuer/grandcarrera.jpg",
    },
    {
        id: "14",
        brand: "Tag Heuer",
        name: "Formula 1",
        price: "35 000€",
        subname: "L'explorateur des profondeurs",
        image: "/tagheuer/formula1.jpg",
    },
    {
        id: "15",
        brand: "Tag Heuer",
        name: "Link",
        price: "35 000€",
        subname: "L'explorateur des profondeurs",
        image: "/tagheuer/link.jpg",
    },
    {
        id: "16",
        brand: "Tag Heuer",
        name: "Aquaracer",
        price: "35 000€",
        subname: "L'explorateur des profondeurs",
        image: "/tagheuer/aquaracer.jpg",
    },
];

export default items;
